# Generated by Django 5.2.4 on 2025-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='Vohrla', max_length=200),
        ),
    ]
