# Generated by Django 5.2.6 on 2025-12-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_alter_sitesetting_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Buy, sell, or book services — student merch, second-hand textbooks, project services, snacks, and more.', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_line1',
            field=models.CharField(blank=True, default='A place to discover', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_line2',
            field=models.CharField(blank=True, default='your marketplace.', max_length=200, null=True),
        ),
    ]
