# Generated by Django 5.2.6 on 2025-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_sitesetting_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address_1',
            field=models.TextField(blank=True, default='123 Innovation Avenue, Suite 456\nSan Francisco, CA 94107, USA', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address_2',
            field=models.TextField(blank=True, default='789 Digital Plaza, Floor 10\nNew York, NY 10001, USA', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='contact@monetatech.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone_1',
            field=models.CharField(blank=True, default='+1 (555) 123-4567', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone_2',
            field=models.CharField(blank=True, default='+1 (555) 987-6543 (Support)', max_length=200, null=True),
        ),
    ]
