# Generated by Django 5.2.6 on 2025-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_sitesetting_contact_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(default='contact@monetatech.com', max_length=254)),
                ('primary_phone', models.CharField(default='+1 (555) 123-4567', max_length=200)),
                ('primary_address', models.TextField(default='123 Innovation Avenue, Suite 456\nSan Francisco, CA 94107, USA')),
                ('support_phone', models.CharField(default='+1 (555) 987-6543 (Support)', max_length=200)),
                ('support_address', models.TextField(default='789 Digital Plaza, Floor 10\nNew York, NY 10001, USA')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/companyname', null=True)),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/15551234567', null=True)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/companyname', null=True)),
                ('tiktok_url', models.URLField(blank=True, default='https://www.tiktok.com/@companyname', null=True)),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@companyname', null=True)),
                ('wechat_url', models.URLField(blank=True, default='mailto:contact@monetatech.com', null=True)),
            ],
            options={
                'verbose_name': 'Contact Setting',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
    ]
