# Generated by Django 5.2.6 on 2025-11-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
