# Generated by Django 5.2.6 on 2025-11-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10, unique=True),
        ),
    ]
